name: Use secret as input
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Use secret in an action
        uses: actions/checkout@v5
        with:
          api_key: ${{ secrets.API_KEY }}
